<html>
	<style type="text/css">
		@import url("../estilos/estilo_menu_vertical.css");
	</style>
	</style>
	</head>
	<!--trabalhar nisso-->
	<body>
		<br/>
		<br/>

		<div id="menu">
			<li>
				<ul>
					<a href="../pagina_inicial/index.php">Home</a>
				</ul>
				<ul>
					<a href="../carrinho_3/busca_produtos.php">Pesquisa de produtos</a>
				</ul>
				<ul>
					<a href="../carrinho_3/carrinho.php">Carrinho de compras</a>
				</ul>
				<ul>
					<a href="">Sobre n&oacute;s</a>
				</ul>
				<ul>
					<a href="">Contato</a>
				</ul>
			</li>
		</div>

		<br/>
		<br/>
</html>