<!doctype html>
<html lang="pt-br">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link rel="stylesheet" href="../estilos/estilo_tabela.css" type="text/css">
		</style>
<?php

echo $tabela = '<table width="900px" border="1" align="center" cellspacing="0" cellpadding="10">';
//imprime o cabecalho da tabela de resultados

echo $tabela = '<tr class="table-topo">
	   
				<td width="30%" align="center">
				<topic>Produto</topic>
                 </td>
                 <td width="10%" align="center">
				<topic>Fornecedor</topic>
                 </td>
                  <td width="10%" align="center">
                 <topic>Qtd Estoque</topic>
                 </td>
                 <td width="10%" align="center">
                 <topic>Qtd Desejada</topic>
                 </td>
                 <td width="15%" align="center">
                 <topic>Preço de venda</topic>
                 </td>
                 <td width="25%" align="center">
                 <topic>Colocar no carrinho</topic>
                 </td>
                

	   </tr>';
?>   

</html>